In [1]:
import numpy as np

# Numpy e soma de vetores

In [2]:
np_peso = np.array([1,2,3,4,5])

In [3]:
np_altura = np.array([2,3,4,5,6])

In [4]:
np_total = np_peso + np_altura

In [5]:
np_total

array([ 3,  5,  7,  9, 11])

## Rodando valores Numpy dentro de um for com .nditer()

In [6]:
# Juntando vetores e formando uma matriz

In [7]:
np_juntos = np.array([np_altura,np_peso])

In [8]:
np_juntos

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [9]:
# np_juntos [todas_linhas, da coluna 0 até a 1]
np_juntos[:,:2]

array([[2, 3],
       [1, 2]])

In [10]:
for x in np.nditer(np_juntos):
    print(x)

2
3
4
5
6
1
2
3
4
5


# BOOLEAN OPERATORS

In [11]:
# np.logical_and( # primeiro bool, segundo bool)

In [12]:
# np.logical_or()

In [13]:
# np.logical_not()

# Functions estatisticas

## .mean()

In [17]:
np.mean(np_a)

5.5

## .median()

In [14]:
np.median(np_a)

5.5

## .std()

In [16]:
np.std(np_a)

2.8722813232690143

## .corrcoef()

In [15]:
np.corrcoef(np_a[0],np_a[1])

array([[1., 1.],
       [1., 1.]])

## random.normal()
<p> cria distribuição normal. </p>

In [18]:
np.random.normal(1.75,0.2,10)

array([2.01862292, 2.03820123, 1.8339527 , 1.60790947, 1.59164807,
       1.85168202, 1.69518743, 1.74232146, 1.99778228, 1.79390362])

# Outras Funções

## .ravel()
<p> Transforma uma matriz num vetor. </p>

In [3]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array.ravel()

array([1, 2, 3, 4, 5, 6])

In [5]:
array.T.ravel()

array([1, 4, 2, 5, 3, 6])

## .reshape()
<p> Aumenta dimensões de um array. </p>

In [11]:
array2 = np.array([1,2,3,4,5,6])

In [13]:
array2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## .vstack() .hstack() .column_stack()
<p> União de arrays. </p>

In [15]:
array3 = np.array([1,2,3])
array4 = np.array([4,5,6])

In [16]:
np.vstack((array3,array4))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.hstack((array3,array4))

array([1, 2, 3, 4, 5, 6])

In [19]:
np.column_stack((array3,array4))

array([[1, 4],
       [2, 5],
       [3, 6]])

## np.hsplit()
<p>split de arrays</p>

In [21]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a,b,c = np.hsplit(array,3)

In [25]:
a

array([[1],
       [4]])

In [26]:
b

array([[2],
       [5]])

In [27]:
c

array([[3],
       [6]])

## np.dot
<p> Mutiplica Matrizes </p>